### ISSUE TITLE
dist/index.js is ES6?

### ISSUE THREAD

**Issue by kinglywork** [nozzlegear/react-svg-progress#1]
I installed react-svg-progress from npm and I found that dist/index.js is in ES6, there will be error while bundle our package with Uglify:

ERROR in vendor.098cae2d3c4080484124.js from UglifyJs
Unexpected token: name (Dialog) [./~/react-svg-progress/dist/index.js:4,0][vendor.098cae2d3c4080484124.js:116453,6]

**Comment by nozzlegear** [comment]
Thanks for reporting this! I switched the TypeScript compilation to target ES5 and published a new version (1.2.0). Let me know if that fixes the problem.
